15 feat 설문 조회 기능을 구현한다
TEAM-VESTIE/backend pull request #16
Opened 2023-07-05 13:46 UTC by miraekwak

- 단일 설문 조회 기능 구현
- 전체 설문 조회 기능 구현
- 서비스 단위 테스트
- 설문 조회 인수테스트 작성

2023-07-06 00:15 UTC, shin-mallang requested changes
굳굳 고생했어!
자잘한 커맨트 남겼는데 확인해줘!

2023-07-06 00:15 UTC, shin-mallang commented on src/main/java/com/vestie/vestie/survey/application/SurveyService.java
> +    }
ServeyQueryService로 옮겨주면 좋을 것 같아!
@Tx(readOnly = true) 옵션도!

2023-07-06 00:15 UTC, shin-mallang commented on src/main/java/com/vestie/vestie/survey/presentation/SurveyController.java
> +        var allSurvey = surveyService.getAllSurvey();
이것도 컨벤션 정해야 할 것 같아!
나는 기본적으로는 안 쓰는 편이긴 해서!
이따 얘기해보장

2023-07-06 00:15 UTC, shin-mallang commented on src/test/java/com/vestie/vestie/acceptance/survey/SurveyAcceptanceSteps.java
> +
공백 제거 부탁해!

2023-07-06 00:15 UTC, shin-mallang commented on src/test/java/com/vestie/vestie/acceptance/survey/SurveyAcceptanceSteps.java
여기두 공백 제거 부탁해!

2023-07-06 00:15 UTC, shin-mallang commented on src/test/java/com/vestie/vestie/acceptance/survey/SurveyAcceptanceSteps.java
> +
여기두 공백 제거!

2023-07-06 00:15 UTC, shin-mallang commented on src/test/java/com/vestie/vestie/acceptance/survey/SurveyAcceptanceTest.java
> +            var 설문_등록_응답 = 설문_등록_요청("베스티 선호도 설문조사", "http://vestie.vestie", LocalDateTime.now());
`LocalDateTime.now()` 는 `CommonSteps`에 `현재시간`으로 세팅해주고 사용하면 더 이쁠 것 같아!

2023-07-06 00:15 UTC, shin-mallang commented on src/test/java/com/vestie/vestie/acceptance/survey/SurveyAcceptanceTest.java
> +            설문_등록_요청("베스티 선호도 설문조사1", "http://vestie.vestie", LocalDateTime.now());
마찬가지!

2023-07-06 00:15 UTC, shin-mallang commented on src/test/java/com/vestie/vestie/acceptance/survey/SurveyAcceptanceTest.java
> +
마찬가지!

2023-07-06 00:15 UTC, shin-mallang commented on src/test/java/com/vestie/vestie/acceptance/survey/SurveyAcceptanceTest.java
> +            ExtractableResponse<Response> 설문_조회_응답 = 전체_설문_조회_요청();
var !

2023-07-06 00:15 UTC, shin-mallang commented on src/test/java/com/vestie/vestie/acceptance/survey/SurveyAcceptanceTest.java
> +            ExtractableResponse<Response> 설문_조회_응답 = 설문_조회_요청(1L);
var !

2023-07-06 00:15 UTC, shin-mallang commented on src/test/java/com/vestie/vestie/survey/application/SurveyServiceTest.java
> +
없으면 제거해줘!

2023-07-06 00:15 UTC, shin-mallang commented on src/test/java/com/vestie/vestie/survey/application/SurveyServiceTest.java
> +
마찬가지!

2023-07-06 00:15 UTC, shin-mallang commented on src/test/java/com/vestie/vestie/survey/application/SurveyServiceTest.java
> +            var getSurvey = surveyService.getSurvey(survey.id());
이거 var에 대해서도 얘기해보자.
나는 일케 보면 반환 타입이 뭔지 안 보여서 불편한 점이 조금 있어!

2023-07-06 00:15 UTC, shin-mallang commented on src/test/java/com/vestie/vestie/survey/domain/FakeSurveyRepository.java
> +            surveyList.add(s);
s 대신 survey

2023-07-06 11:32 UTC, miraekwak commented on src/main/java/com/vestie/vestie/survey/application/SurveyService.java
> +    }
아맞다!!! 얼릉 옮길겡ㅜㅜ

2023-07-06 11:47 UTC, miraekwak commented on src/test/java/com/vestie/vestie/survey/application/SurveyServiceTest.java
> +            var getSurvey = surveyService.getSurvey(survey.id());
인수테스트에서만 var 쓰는걸루 하자!

2023-07-06 13:09 UTC, shin-mallang requested changes
이전에 아직 반영 안된거랑, 추가적으로 몇 개 더 남겼엉!

2023-07-06 13:09 UTC, shin-mallang commented on src/main/java/com/vestie/vestie/survey/application/SurveyQueryService.java
> +
한 줄 !

2023-07-06 13:09 UTC, shin-mallang commented on src/main/java/com/vestie/vestie/survey/application/SurveyQueryService.java
> +        for (Survey s : surveyList) {
s 대신 servey!

2023-07-06 13:09 UTC, shin-mallang commented on src/test/java/com/vestie/vestie/acceptance/survey/SurveyAcceptanceSteps.java
> +    ) {
```suggestion
    public static ExtractableResponse<Response> 전체_설문_조회_요청 () {
```

2023-07-06 13:09 UTC, shin-mallang commented on src/test/java/com/vestie/vestie/survey/application/SurveyServiceTest.java
> +            surveyRepository.save(surveyRegisterCommand.toDomain(member));
굳이 Command -> Domain 으로 넘어가는거 말고,
ServeyFixture을 활용해서 Servey를 바로 저장하는게 더 깔끔해질 것 같아!

2023-07-09 04:25 UTC, miraekwak commented on src/test/java/com/vestie/vestie/survey/application/SurveyServiceTest.java
> +            surveyRepository.save(surveyRegisterCommand.toDomain(member));
왜 SurveyFixture 사용할 생각을 못했지?! 바꿀겡:)

2023-07-10 02:40 UTC, shin-mallang approved these changes, later dismissed
그 뭐지 주석이랑, 맨 첫 리뷰에 LocalDateTime이랑 var 부분 comment 남긴거 있는데 그것만 하고 바로 머지하면 될 것 같옹

2023-07-10 02:40 UTC, shin-mallang commented on src/test/java/com/vestie/vestie/survey/application/SurveyServiceTest.java
> +//            surveyRepository.save(surveyRegisterCommand.toDomain(member));
주석 지워줭!

2023-07-13 12:41 UTC, miraekwak commented on src/test/java/com/vestie/vestie/survey/application/SurveyServiceTest.java
> +//            surveyRepository.save(surveyRegisterCommand.toDomain(member));
맨 첫리뷰에서 왜 저걸 못봤지??? 바로 고쳤엉ㅜㅜ 리뷰 고마워~

2023-07-14 03:44 UTC, shin-mallang approved these changes
고생했어 굳굳~👍

2023-07-15 12:44 UTC, merged